import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import { Toaster } from 'react-hot-toast';


const gmarketSans = localFont({
  src: [
    {
      path: '../fonts/GmarketSansLight.otf',
      weight: '300',
    },
    {
      path: '../fonts/GmarketSansMedium.otf',
      weight: '500',
    },
    {
      path: '../fonts/GmarketSansBold.otf',
      weight: '700',
    },
  ],
  display: 'swap',
  variable: '--font-gmarket',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${gmarketSans.className} bg-white dark:bg-gray-900`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
