name: Nextjs CI/CD (Dev)

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up latest Node.js LTS version
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Configure AWS Credentials for OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GitHubActionsDeploymentRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2 (Dev)
        run: |
          echo "${{ secrets.DEV_EC2_SSH_PRIVATE_KEY_DEV }}" > private_key.pem
          chmod 400 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.DEV_EC2_PUBLIC_IP }} "cd /home/ec2-user/front && bash deploy.sh"